# config context path to "/" by setting an empty string
server:
  contextPath:

jwt:
  header: Authorization
  #mySecret
  secret: ${JWT_SECRET}
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level.: ${PT_LOG_LEVEL}

facebook:
    #1422830621123522
    app_id: ${FACEBOOK_APPID}
    #c6eecfd6f55affa5d5e7c723d1920349    
    app_secret: ${FACEBOOK_APPSECRET}

planttagger:
    uploadpath: /data/file/
    
spring:
    #data
    data:
        neo4j:
            #http://localhost:7474
            URI: ${PT_DB_HOST}
            #neo4j
            username: ${PT_DB_USERNAME}
            #neo4j123
            password: ${PT_DB_PASSWORD}
    #mail
    mail:
        #smtp.gmail.com
        host: ${MAIL_HOST}
        #587
        port: ${MAIL_PORT}
        #chunyap28@gmail.com
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
    #rabbit
    rabbitmq:
        #5672
        port: ${MQ_PORT}
        #guest
        username: ${MQ_USERNAME}
        #guest
        password: ${MQ_PASSWORD}
        #localhost
        host: ${MQ_HOST}
    #jackson
    jackson:
    serialization:
      INDENT_OUTPUT: true
